server:
  port: 8006

spring:
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   #服务注册中心
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    port: 6379
    host: 192.168.31.133
    database: 1
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

oss:
  endpoint: xxxx
  accessKeyId: xxx
  accessKeySecret: xxx
  bucketName: xxxx
  bucketNamePublic: xxxx
  minChunkSize: 100